// exercises.js — Catálogo completo de ejercicios KegeFit Pro

const EXERCISES = {
  kegel_slow: {
    id: 'kegel_slow',
    name: 'Kegel Lento',
    category: 'kegel',
    icon: '🔵',
    targetMuscle: 'Fibras Tipo I (resistencia)',
    benefit: 'Sostiene la erección durante más tiempo',
    difficulty: 1,
    type: 'contract_relax',
    description: 'El ejercicio base. Contrae el músculo pubococcígeo lentamente y mantenelo sostenido. Ideal para construir resistencia muscular.',
    howTo: [
      'Encontrá los músculos: imaginá que querés cortar el flujo de orina',
      'Contraé lentamente, como si subieras un ascensor piso a piso',
      'Sostené la contracción el tiempo indicado',
      'Relajá completamente — la relajación es tan importante como la contracción',
      'No aprietes glúteos, muslos ni abdomen',
    ],
    tip: 'Si sentís que el pene se mueve hacia adentro y el escroto sube levemente, estás haciendo bien el ejercicio.',
    phases: [
      { name: 'Contracción', duration: 5, instruction: 'Contraé y sostenelo', color: '#00C896' },
      { name: 'Relajación', duration: 5, instruction: 'Relajá completamente', color: '#4A9EFF' },
    ],
    defaultReps: 10,
    defaultSets: 3,
  },
  kegel_fast: {
    id: 'kegel_fast',
    name: 'Kegel Rápido',
    category: 'kegel',
    icon: '⚡',
    targetMuscle: 'Fibras Tipo II (potencia)',
    benefit: 'Máxima rigidez eréctil en el momento',
    difficulty: 1,
    type: 'pulses',
    description: 'Pulsos rápidos y potentes. Entrena las fibras de contracción rápida, responsables de la rigidez pico durante la erección.',
    howTo: [
      'Contraé el músculo tan rápido y fuerte como puedas',
      'Soltá inmediatamente (1 segundo máximo)',
      'Repetí el pulso',
      'Mantené un ritmo constante como un latido',
    ],
    tip: 'Pensá en encender y apagar — cada pulso tiene que ser el 100% de tu fuerza.',
    phases: [
      { name: 'Pulso', duration: 1, instruction: 'Contraé con fuerza máxima', color: '#FFD700' },
      { name: 'Soltá', duration: 1, instruction: 'Relajá completamente', color: '#4A9EFF' },
    ],
    defaultReps: 15,
    defaultSets: 3,
  },
  kegel_super: {
    id: 'kegel_super',
    name: 'Super Kegel',
    category: 'kegel',
    icon: '💪',
    targetMuscle: 'Isquiocavernoso + Bulbocavernoso',
    benefit: 'Máxima fuerza isométrica del piso pélvico',
    difficulty: 3,
    type: 'contract_relax',
    description: 'Contracción máxima sostenida. Recluta todos los músculos del piso pélvico al 100% de su capacidad. Es el ejercicio más intenso.',
    howTo: [
      'Encontrá los músculos como en el Kegel Lento',
      'Inhalá profundo',
      'Al exhalar, contraé con el MÁXIMO esfuerzo posible',
      'Mantené esa contracción máxima el tiempo indicado',
      'Relajá completamente y respirá normalmente',
    ],
    tip: 'Hacé pocas repeticiones de calidad — es preferible 5 repeticiones perfectas a 15 mediocres.',
    phases: [
      { name: 'Contracción Máxima', duration: 8, instruction: '100% de fuerza — aguantá', color: '#FF4757' },
      { name: 'Recuperación', duration: 10, instruction: 'Relajá todo completamente', color: '#4A9EFF' },
    ],
    defaultReps: 5,
    defaultSets: 2,
  },
  kegel_elevator: {
    id: 'kegel_elevator',
    name: 'Kegel Ascensor',
    category: 'kegel',
    icon: '🏗️',
    targetMuscle: 'Control neuromuscular del piso pélvico',
    benefit: 'Control y conciencia corporal profunda',
    difficulty: 3,
    type: 'elevator',
    description: 'Contracción progresiva en 5 pisos. Mejora el control neuromuscular y la conciencia corporal del piso pélvico.',
    howTo: [
      'Contraé el 20% de tu capacidad (Piso 1) — mantené 2s',
      'Subí al 40% (Piso 2) — mantené 2s',
      'Subí al 60% (Piso 3) — mantené 2s',
      'Subí al 80% (Piso 4) — mantené 2s',
      'Subí al 100% (Piso 5) — mantené 3s',
      'Bajá piso por piso de la misma forma',
    ],
    tip: 'Visualizá que un ascensor sube lentamente. Cada piso es una contracción más intensa.',
    phases: [
      { name: 'Piso 1 — 20%', duration: 2, instruction: 'Contracción muy suave', color: '#A8FF78' },
      { name: 'Piso 2 — 40%', duration: 2, instruction: 'Un poco más', color: '#78FFB6' },
      { name: 'Piso 3 — 60%', duration: 2, instruction: 'Mitad de tu fuerza', color: '#00C896' },
      { name: 'Piso 4 — 80%', duration: 2, instruction: 'Casi al máximo', color: '#00A37D' },
      { name: 'Piso 5 — 100%', duration: 3, instruction: 'Máximo esfuerzo', color: '#008060' },
      { name: 'Piso 4 — 80%', duration: 2, instruction: 'Bajando suavemente', color: '#00A37D' },
      { name: 'Piso 3 — 60%', duration: 2, instruction: 'Relajando más', color: '#00C896' },
      { name: 'Piso 2 — 40%', duration: 2, instruction: 'Casi relajado', color: '#78FFB6' },
      { name: 'Piso 1 — 20%', duration: 2, instruction: 'Soltando casi todo', color: '#A8FF78' },
      { name: 'Relajación', duration: 10, instruction: 'Relajá completamente', color: '#4A9EFF' },
    ],
    defaultReps: 5,
    defaultSets: 2,
  },
  kegel_reverse: {
    id: 'kegel_reverse',
    name: 'Kegel Inverso',
    category: 'kegel',
    icon: '🔄',
    targetMuscle: 'Relajación activa del piso pélvico',
    benefit: 'Libera tensión acumulada, mejora el flujo sanguíneo',
    difficulty: 2,
    type: 'breathe_relax',
    description: 'Relajación activa del piso pélvico. Un músculo que no puede relajarse completamente tampoco puede contraerse con fuerza máxima.',
    howTo: [
      'Inhalá profundo expandiendo el abdomen (no el pecho)',
      'Mientras inhalás, abrí y relajá activamente el piso pélvico',
      'Sentís como si empujaras suavemente hacia afuera',
      'Al exhalar, soltá el esfuerzo sin contraer',
    ],
    tip: 'Este ejercicio es especialmente útil si tu piso pélvico está demasiado tenso (hipertonía).',
    phases: [
      { name: 'Inhalación + Apertura', duration: 5, instruction: 'Expandí el abdomen, abrí el piso pélvico', color: '#A8FF78' },
      { name: 'Exhalación', duration: 5, instruction: 'Soltá sin contraer', color: '#4A9EFF' },
    ],
    defaultReps: 10,
    defaultSets: 2,
  },
  kegel_pulsing: {
    id: 'kegel_pulsing',
    name: 'Kegel Pulsante',
    category: 'kegel',
    icon: '💫',
    targetMuscle: 'Coordinación neuromuscular rápida',
    benefit: 'Mejora el control durante el acto sexual',
    difficulty: 2,
    type: 'pulses_timed',
    description: 'Series de pulsos rítmicos de velocidad media. Entrena la coordinación y el control durante el acto sexual.',
    howTo: [
      'Contraé y soltá en ritmo constante',
      'Cada pulso dura 2 segundos',
      'Mantené la postura y la respiración',
      'No aprietes otras zonas',
    ],
    tip: 'Podés practicar este durante el día sin que nadie lo note — sentado en el trabajo, en el colectivo, etc.',
    phases: [
      { name: 'Contracción', duration: 2, instruction: 'Contraé', color: '#00C896' },
      { name: 'Relajación', duration: 2, instruction: 'Soltá', color: '#4A9EFF' },
    ],
    defaultReps: 20,
    defaultSets: 3,
  },
  glute_bridge: {
    id: 'glute_bridge',
    name: 'Puente de Glúteos',
    category: 'strength',
    icon: '🌉',
    targetMuscle: 'Glúteos, isquiotibiales, piso pélvico',
    benefit: 'Base esencial — activa la cadena posterior completa',
    difficulty: 1,
    type: 'hold_and_lower',
    description: 'El ejercicio complementario más importante. Fortalece los glúteos y la cadena posterior que dan soporte estructural al piso pélvico.',
    howTo: [
      'Acostado boca arriba, rodillas dobladas, pies planos en el suelo',
      'Brazos a los lados, palmas hacia abajo',
      'Inhalá profundo',
      'Al exhalar, levantá la pelvis apretando los glúteos',
      'Opcional: al llegar arriba, contraé el Kegel también',
      'Bajá lentamente con control',
    ],
    tip: 'El cuerpo debe formar una línea recta desde los hombros hasta las rodillas.',
    phases: [
      { name: 'Subida', duration: 2, instruction: 'Levantá la pelvis lentamente', color: '#00C896' },
      { name: 'Pausa arriba', duration: 3, instruction: 'Apretá glúteos + opcional Kegel', color: '#FFD700' },
      { name: 'Bajada', duration: 2, instruction: 'Bajá con control', color: '#4A9EFF' },
    ],
    defaultReps: 12,
    defaultSets: 3,
  },
  bridge_elevated: {
    id: 'bridge_elevated',
    name: 'Puente Elevado',
    category: 'strength',
    icon: '🏔️',
    targetMuscle: 'Glúteos, isquiotibiales, core, piso pélvico',
    benefit: 'Mayor intensidad y rango de movimiento',
    difficulty: 2,
    type: 'hold_and_lower',
    description: 'Variación con pausa isométrica prolongada en la cima. Aumenta la intensidad del trabajo muscular.',
    howTo: [
      'Igual que el Puente de Glúteos básico',
      'Al llegar arriba, apretá al máximo los glúteos',
      'Hacé un Kegel sostenido mientras estás arriba',
      'Mantené la posición el tiempo indicado',
      'Bajá muy lentamente',
    ],
    tip: 'La pausa isométrica es donde ocurre el mayor trabajo muscular.',
    phases: [
      { name: 'Subida', duration: 2, instruction: 'Levantá con control', color: '#00C896' },
      { name: 'Pausa isométrica', duration: 5, instruction: 'Apretá glúteos + Kegel al máximo', color: '#FF4757' },
      { name: 'Bajada lenta', duration: 3, instruction: 'Bajá muy lentamente, controlando', color: '#4A9EFF' },
    ],
    defaultReps: 10,
    defaultSets: 3,
  },
  bridge_unilateral: {
    id: 'bridge_unilateral',
    name: 'Puente Unilateral',
    category: 'strength',
    icon: '🦵',
    targetMuscle: 'Glúteo unilateral, estabilizadores de cadera',
    benefit: 'Corrección de asimetrías musculares',
    difficulty: 3,
    type: 'hold_and_lower',
    description: 'Puente con una sola pierna. Detecta y corrige desequilibrios musculares entre los lados derecho e izquierdo.',
    howTo: [
      'Posición inicial igual al puente básico',
      'Extendé una pierna recta (paralela al suelo)',
      'Levantá la pelvis con una sola pierna',
      'Mantené la cadera nivelada — no la dejes caer hacia un lado',
      'Alternás entre pierna derecha e izquierda',
    ],
    tip: 'Si un lado es mucho más débil, hacé más repeticiones de ese lado.',
    phases: [
      { name: 'Subida (pierna derecha)', duration: 2, instruction: 'Levantá con la pierna derecha', color: '#00C896' },
      { name: 'Pausa', duration: 3, instruction: 'Mantené la posición', color: '#FFD700' },
      { name: 'Bajada', duration: 2, instruction: 'Bajá lentamente', color: '#4A9EFF' },
    ],
    defaultReps: 10,
    defaultSets: 2,
  },
  pelvic_squat: {
    id: 'pelvic_squat',
    name: 'Sentadilla Pélvica',
    category: 'strength',
    icon: '🏋️',
    targetMuscle: 'Cuádriceps, glúteos, piso pélvico bajo carga',
    benefit: 'Activa el periné en posición funcional de carga',
    difficulty: 2,
    type: 'squat',
    description: 'Sentadilla convencional con activación consciente del piso pélvico. Integra el piso pélvico en movimientos funcionales cotidianos.',
    howTo: [
      'Pies a la anchura de los hombros',
      'Bajá como si te fueras a sentar en una silla',
      'Durante la SUBIDA: exhalar y contraer el Kegel',
      'Durante la BAJADA: inhalar y relajar el piso pélvico',
      'Espalda recta, rodillas sobre los pies',
    ],
    tip: 'La regla es: exhalar + contraer al esfuerzo. Esto se aplica también en la vida diaria al levantar peso.',
    phases: [
      { name: 'Bajada', duration: 3, instruction: 'Inhalá y relajá el piso pélvico', color: '#4A9EFF' },
      { name: 'Pausa abajo', duration: 1, instruction: 'Posición final', color: '#FFD700' },
      { name: 'Subida', duration: 2, instruction: 'Exhalá + contraé Kegel', color: '#00C896' },
    ],
    defaultReps: 12,
    defaultSets: 3,
  },
  sumo_squat: {
    id: 'sumo_squat',
    name: 'Sentadilla Sumo',
    category: 'strength',
    icon: '🥋',
    targetMuscle: 'Aductores, glúteos, suelo pélvico',
    benefit: 'Apertura de cadera + activación del suelo pélvico',
    difficulty: 2,
    type: 'squat',
    description: 'Sentadilla con piernas abiertas y pies hacia afuera. Trabaja los aductores internos que sustentan el piso pélvico desde los lados.',
    howTo: [
      'Pies más amplios que los hombros, puntillas hacia afuera (~45°)',
      'Manos juntas frente al pecho',
      'Bajá lentamente manteniendo las rodillas alineadas con los pies',
      'Llegá tan bajo como puedas con la espalda recta',
      'Subí apretando glúteos y aductores',
    ],
    tip: 'La amplitud de la sentadilla sumo abre la región pélvica, mejorando la circulación y flexibilidad en esa zona.',
    phases: [
      { name: 'Bajada', duration: 3, instruction: 'Bajá con control', color: '#4A9EFF' },
      { name: 'Pausa abajo', duration: 2, instruction: 'Mantené la posición', color: '#FFD700' },
      { name: 'Subida', duration: 2, instruction: 'Subí apretando glúteos', color: '#00C896' },
    ],
    defaultReps: 12,
    defaultSets: 3,
  },
  hypopressive: {
    id: 'hypopressive',
    name: 'Hipopresivo',
    category: 'strength',
    icon: '🌀',
    targetMuscle: 'Transverso abdominal, diafragma, piso pélvico',
    benefit: 'Mejora circulación perineal y tono abdominal profundo',
    difficulty: 3,
    type: 'breathe_hold',
    description: 'Técnica de vacío abdominal. Reduce la presión intraabdominal, mejora la oxigenación del periné y trabaja el core profundo.',
    howTo: [
      'Sentado o de pie con postura erecta',
      'Inhalá profundo por la nariz',
      'Exhalá todo el aire por la boca lentamente',
      'Con los pulmones vacíos, abrí las costillas hacia afuera',
      'Metí el abdomen hacia adentro y hacia arriba (vacío)',
      'Aguantá en apnea el tiempo indicado',
      'Inhalá suavemente para salir',
    ],
    tip: 'No hagas este ejercicio si tenés hipertensión arterial sin consultar antes con tu médico.',
    phases: [
      { name: 'Inhalación', duration: 3, instruction: 'Inhalá profundo por la nariz', color: '#A8FF78' },
      { name: 'Exhalación', duration: 4, instruction: 'Soltá todo el aire lentamente', color: '#4A9EFF' },
      { name: 'Apnea + Vacío', duration: 8, instruction: 'Pulmones vacíos — abrí costillas, metí abdomen', color: '#FFD700' },
      { name: 'Inhalación de salida', duration: 3, instruction: 'Inhalá suavemente', color: '#A8FF78' },
      { name: 'Recuperación', duration: 5, instruction: 'Respirá normalmente', color: '#4A9EFF' },
    ],
    defaultReps: 5,
    defaultSets: 3,
  },
  childs_pose: {
    id: 'childs_pose',
    name: 'Postura del Niño',
    category: 'stretch',
    icon: '🧘',
    targetMuscle: 'Piso pélvico (relajación), lumbar, caderas',
    benefit: 'Relajación profunda del piso pélvico post-entrenamiento',
    difficulty: 1,
    type: 'hold_stretch',
    description: 'Estiramiento de yoga fundamental para relajar el piso pélvico después de la sesión. Permite que los músculos se recuperen correctamente.',
    howTo: [
      'Arrodilláte en el suelo',
      'Separáte las rodillas al ancho de la colchoneta',
      'Juntá los dedos gordos de los pies',
      'Extendé los brazos hacia adelante y bajá el cuerpo',
      'La frente toca el suelo',
      'Respirá profundo — sentís cómo el piso pélvico se abre',
    ],
    tip: 'Respirá hacia la espalda baja y el piso pélvico — sentís cómo se expande con cada inhalación.',
    phases: [
      { name: 'Postura del Niño', duration: 60, instruction: 'Respirá profundo y relajá completamente el piso pélvico', color: '#A8D8EA' },
    ],
    defaultReps: 1,
    defaultSets: 1,
    isStretch: true,
  },
  butterfly: {
    id: 'butterfly',
    name: 'Mariposa',
    category: 'stretch',
    icon: '🦋',
    targetMuscle: 'Aductores, caderas, periné',
    benefit: 'Apertura de cadera — mejora circulación en la zona pélvica',
    difficulty: 1,
    type: 'hold_stretch',
    description: 'Estiramiento clásico de apertura de caderas. Mejora la flexibilidad de los aductores y la circulación en el periné.',
    howTo: [
      'Sentáte en el suelo con las piernas extendidas',
      'Doblá las rodillas y uní las plantas de los pies',
      'Tomá los pies con ambas manos',
      'Dejá caer suavemente las rodillas hacia los costados',
      'Presioná levemente con los codos en los muslos para aumentar el estiramiento',
    ],
    tip: 'No fuerces las rodillas hacia abajo — dejalas caer por gravedad y respiración.',
    phases: [
      { name: 'Mariposa', duration: 45, instruction: 'Relajá las caderas, respirá y dejá caer las rodillas', color: '#A8D8EA' },
    ],
    defaultReps: 1,
    defaultSets: 2,
    isStretch: true,
  },
  figure_four: {
    id: 'figure_four',
    name: 'Figura 4',
    category: 'stretch',
    icon: '4️⃣',
    targetMuscle: 'Piriforme, glúteos, cadera externa',
    benefit: 'Libera tensión glútea que afecta el suelo pélvico',
    difficulty: 1,
    type: 'hold_stretch',
    description: 'Estiramiento del músculo piriforme y glúteo. La tensión en el piriforme puede comprimir el nervio pudendo, afectando la función sexual.',
    howTo: [
      'Acostado boca arriba, rodillas dobladas',
      'Cruzá el tobillo derecho sobre la rodilla izquierda',
      'Levantá la pierna izquierda hacia el pecho',
      'Tomá el muslo izquierdo con las dos manos',
      'Tirá suavemente hacia vos hasta sentir el estiramiento en el glúteo derecho',
      'Alternáte entre ambos lados',
    ],
    tip: 'Si sentís un hormigueo o adormecimiento, es el nervio. Soltá un poco la presión.',
    phases: [
      { name: 'Figura 4 (derecha)', duration: 30, instruction: 'Sentís el estiramiento en el glúteo derecho', color: '#A8D8EA' },
      { name: 'Cambio de lado', duration: 5, instruction: 'Cambiá de pierna', color: '#FFD700' },
      { name: 'Figura 4 (izquierda)', duration: 30, instruction: 'Sentís el estiramiento en el glúteo izquierdo', color: '#A8D8EA' },
    ],
    defaultReps: 1,
    defaultSets: 2,
    isStretch: true,
  },
  happy_baby: {
    id: 'happy_baby',
    name: 'Happy Baby',
    category: 'stretch',
    icon: '👶',
    targetMuscle: 'Zona lumbar, caderas, piso pélvico',
    benefit: 'Descompresión completa de la región pélvica',
    difficulty: 1,
    type: 'hold_stretch',
    description: 'Postura de yoga para descomprimir la espalda baja y las caderas. Permite al piso pélvico relajarse en posición abierta.',
    howTo: [
      'Acostado boca arriba',
      'Llevá las rodillas al pecho',
      'Tomá la parte interior de los pies (o los tobillos si no llegás)',
      'Abrí las rodillas hacia los costados y llevátelas hacia las axilas',
      'Empujá las plantas de los pies hacia arriba con las manos',
      'Balanceáte suavemente si te resulta cómodo',
    ],
    tip: 'La espalda baja debe estar plana sobre el suelo. Si se levanta, tomá los tobillos en lugar de los pies.',
    phases: [
      { name: 'Happy Baby', duration: 60, instruction: 'Respirá profundo y relajá todo. Dejáte ir.', color: '#A8D8EA' },
    ],
    defaultReps: 1,
    defaultSets: 1,
    isStretch: true,
  },
  piriformis_stretch: {
    id: 'piriformis_stretch',
    name: 'Estiramiento Piriforme',
    category: 'stretch',
    icon: '🔀',
    targetMuscle: 'Piriforme, rotadores externos de cadera',
    benefit: 'Libera compresión del nervio pudendo',
    difficulty: 2,
    type: 'hold_stretch',
    description: 'El músculo piriforme, cuando está tenso, puede comprimir el nervio pudendo afectando la sensibilidad y función eréctil.',
    howTo: [
      'De pie, cruzá el pie derecho sobre la rodilla izquierda',
      'Doblá la rodilla izquierda lentamente',
      'Inclináte hacia adelante con la espalda recta',
      'Sentís el estiramiento profundo en el glúteo derecho',
      'Sostené y cambiá de lado',
    ],
    tip: 'Podés hacerlo apoyándote en una silla o pared para no perder el equilibrio.',
    phases: [
      { name: 'Piriforme derecho', duration: 30, instruction: 'Inclinaciones suaves, espalda recta', color: '#A8D8EA' },
      { name: 'Cambio', duration: 5, instruction: 'Cambiá de pierna', color: '#FFD700' },
      { name: 'Piriforme izquierdo', duration: 30, instruction: 'Inclinaciones suaves, espalda recta', color: '#A8D8EA' },
    ],
    defaultReps: 1,
    defaultSets: 2,
    isStretch: true,
  },
  diaphragmatic: {
    id: 'diaphragmatic',
    name: 'Respiración Diafragmática',
    category: 'breathing',
    icon: '🫁',
    targetMuscle: 'Diafragma, core profundo, piso pélvico',
    benefit: 'Sincroniza piso pélvico con respiración — función sexual mejorada',
    difficulty: 1,
    type: 'breathe_cycle',
    description: 'El diafragma y el piso pélvico trabajan en sincronía. Al inhalar, el piso pélvico desciende y se abre. Al exhalar, sube. Dominar esto mejora el control sexual.',
    howTo: [
      'Acostado o sentado cómodo',
      'Poné una mano en el pecho y otra en el abdomen',
      'Inhalá por la nariz: el abdomen sube, el pecho casi no se mueve',
      'Al inhalar, sentís que el piso pélvico se abre hacia abajo',
      'Exhalá por la boca lentamente: el abdomen baja',
      'Al exhalar, sentís que el piso pélvico sube suavemente',
    ],
    tip: 'Si la mano del pecho se mueve mucho y la del abdomen poco, estás respirando con el pecho (incorrecto).',
    phases: [
      { name: 'Inhalación', duration: 4, instruction: 'Por la nariz — abdomen sube, piso pélvico se abre', color: '#A8FF78' },
      { name: 'Pausa', duration: 2, instruction: 'Mantené suavemente', color: '#FFD700' },
      { name: 'Exhalación', duration: 6, instruction: 'Por la boca — abdomen baja, piso pélvico sube', color: '#4A9EFF' },
    ],
    defaultReps: 10,
    defaultSets: 2,
  },
  breathing_478: {
    id: 'breathing_478',
    name: 'Respiración 4-7-8',
    category: 'breathing',
    icon: '💆',
    targetMuscle: 'Sistema nervioso parasimpático, reducción del cortisol',
    benefit: 'Reduce ansiedad de performance, relaja el sistema nervioso',
    difficulty: 1,
    type: 'breathe_478',
    description: 'Técnica de respiración del Dr. Andrew Weil. Activa el sistema nervioso parasimpático, reduciendo la ansiedad de rendimiento que es causa común de disfunción eréctil.',
    howTo: [
      'Inhalá 4 segundos por la nariz',
      'Aguantá 7 segundos',
      'Exhalá completamente 8 segundos por la boca',
      'Repetí el ciclo',
    ],
    tip: 'La ansiedad de performance (miedo a no funcionar) es una causa enorme de DE. Esta respiración la combate directamente.',
    phases: [
      { name: 'Inhalación', duration: 4, instruction: 'Por la nariz lentamente', color: '#A8FF78' },
      { name: 'Aguantá', duration: 7, instruction: 'Aguantá el aire', color: '#FFD700' },
      { name: 'Exhalación', duration: 8, instruction: 'Soltá todo el aire por la boca', color: '#4A9EFF' },
    ],
    defaultReps: 8,
    defaultSets: 2,
  },
  kegel_breath_sync: {
    id: 'kegel_breath_sync',
    name: 'Kegel + Respiración',
    category: 'breathing',
    icon: '🎵',
    targetMuscle: 'Piso pélvico + diafragma (coordinación)',
    benefit: 'Integración máxima — técnica avanzada para uso real',
    difficulty: 3,
    type: 'sync',
    description: 'La técnica más avanzada. Coordinás conscientemente la contracción del piso pélvico con la respiración, como ocurre naturalmente durante el acto sexual.',
    howTo: [
      'Inhalá expandiendo el abdomen (piso pélvico se relaja)',
      'Al exhalar: contraé el Kegel suavemente',
      'La contracción dura toda la exhalación',
      'Al inhalar: relajá el Kegel completamente',
      'El ritmo debe ser fluido y sin pausas',
    ],
    tip: 'Esta es la técnica que realmente se usa durante el acto sexual para maximizar la erección y el control.',
    phases: [
      { name: 'Inhalación — Relajar Kegel', duration: 4, instruction: 'Inhalá y relajá el piso pélvico', color: '#A8FF78' },
      { name: 'Exhalación — Contraer Kegel', duration: 6, instruction: 'Exhalá lentamente + Kegel', color: '#00C896' },
    ],
    defaultReps: 10,
    defaultSets: 3,
  },

  // ═══════════════════════════════════════════════════════
  // EJERCICIOS DE KEGEL YOGA & LIBERACIÓN SOMÁTICA
  // ═══════════════════════════════════════════════════════
  reverse_tabletop: {
    id: 'reverse_tabletop',
    name: 'Mesa Invertida (Reverse Tabletop)',
    category: 'strength',
    icon: '🦀',
    targetMuscle: 'Cadena posterior + apertura profunda de psoas y pelvis anterior',
    benefit: 'Desbloquea el flujo arterial hacia la próstata y el pene mientras activa glúteos',
    difficulty: 2,
    type: 'reps',
    description: 'Apoyando manos y pies en el suelo, elevás la pelvis hasta que el torso y los muslos formen una mesa horizontal perfecta. Abre profundamente los flexores de cadera y el psoas ilíaco, permitiendo que la arteria pudenda irrigue sin restricciones.',
    howTo: [
      'Sentate en el suelo con rodillas flexionadas y pies apoyados al ancho de hombros',
      'Colocá las palmas de las manos detrás de tus caderas, dedos apuntando hacia los pies',
      'Empujá con fuerza talones y palmas, elevando la pelvis hacia el techo',
      'Formá una línea recta horizontal desde las rodillas hasta el pecho',
      'Apretá glúteos y piso pélvico en la cima durante 4 segundos y descendé con control',
    ],
    tip: 'No dejes caer la pelvis. Mantené los glúteos apretados y el cuello alineado con la columna.',
    phases: [
      { name: 'Elevación y Sostén Pélvico', duration: 4, instruction: 'Empujá pelvis arriba y apretá glúteos', color: '#00C896' },
      { name: 'Descenso y Control', duration: 3, instruction: 'Bajá con control sin apoyar de golpe', color: '#4A9EFF' },
    ],
    defaultReps: 10,
    defaultSets: 3,
  },

  donkey_kick: {
    id: 'donkey_kick',
    name: 'Patada en Cuadrupedia (Donkey Kick)',
    category: 'strength',
    icon: '🦵',
    targetMuscle: 'Glúteo mayor + estabilización sacra y perineal',
    benefit: 'Aísla el glúteo sin arquear la columna, equilibrando el piso pélvico',
    difficulty: 1,
    type: 'reps',
    description: 'En cuatro apoyos, flexionás la rodilla a 90° y empujás la planta del pie hacia el techo. Aísla el glúteo mayor y activa la fascia pélvica profunda sin compensación lumbar.',
    howTo: [
      'Colocate en cuatro apoyos (manos bajo hombros y rodillas bajo caderas)',
      'Apretá el abdomen para que la espalda baja no se curve',
      'Flexioná la pierna a 90° y elevá el talón hacia el techo',
      'En el punto más alto, apretá el glúteo fuertemente 2 segundos',
      'Bajá lento sin que la rodilla toque el piso y repetí',
    ],
    tip: 'Sentí la contracción profunda en la base del glúteo, donde se une con el suelo pélvico.',
    phases: [
      { name: 'Patada y Apretón de Glúteo', duration: 3, instruction: 'Empujá talón arriba y apretá glúteo', color: '#00C896' },
      { name: 'Retorno Controlado', duration: 2, instruction: 'Bajá lento manteniendo control', color: '#4A9EFF' },
    ],
    defaultReps: 12,
    defaultSets: 3,
  },

  psoas_release: {
    id: 'psoas_release',
    name: 'Liberación de Psoas (Knee to Chest)',
    category: 'stretch',
    icon: '🧘‍♂️',
    targetMuscle: 'Psoas ilíaco + nervio pudendo + plexo prostático',
    benefit: 'Desbloquea la cadena anterior para evitar el tap-out y la sobrexcitación prematura',
    difficulty: 1,
    type: 'hold',
    description: 'Acostado boca arriba, abrazás una rodilla al pecho mientras la otra pierna se proyecta estirada hacia adelante. Estira profundamente el psoas, músculo que al estar tenso estrangula el flujo sanguíneo y nervioso de la pelvis.',
    howTo: [
      'Acostate boca arriba en el mat o suelo',
      'Llevá la rodilla derecha al pecho y abrazala con ambas manos',
      'Mantené la pierna izquierda extendida proyectada hacia adelante',
      'Relajá hombros y cuello, y respirá profundo dirigiendo el aire a la pelvis',
      'Cambiá de pierna al sonar la campana',
    ],
    tip: 'En cada exhalación, soltá conscientemente cualquier tensión en los testículos y el esfínter.',
    phases: [
      { name: 'Rodilla Derecha al Pecho', duration: 25, instruction: 'Abrazá rodilla derecha y respirá profundo', color: '#A8D8EA' },
      { name: 'Cambio de Pierna', duration: 5, instruction: 'Cambiá suavemente de lado', color: '#FFB300', isRest: true },
      { name: 'Rodilla Izquierda al Pecho', duration: 25, instruction: 'Abrazá rodilla izquierda y relajá la pelvis', color: '#A8D8EA' },
    ],
    defaultReps: 1,
    defaultSets: 2,
  },

  reclined_butterfly: {
    id: 'reclined_butterfly',
    name: 'Mariposa Reclinada (Supta Baddha)',
    category: 'stretch',
    icon: '🦋',
    targetMuscle: 'Aductores profundos + suelo pélvico somático + fascia prostática',
    benefit: 'Flujo prostático, alivio de presión y control de la eyaculación precoz',
    difficulty: 1,
    type: 'hold',
    description: 'La postura reina del Kegel Yoga masculino. Acostado boca arriba con plantas de los pies unidas y rodillas cayendo hacia los laterales por gravedad. Abre la cuenca pélvica, alivia la presión prostática y entrena el control somático.',
    howTo: [
      'Acostate boca arriba en el suelo o mat',
      'Juntá las plantas de los pies acercándolos suavemente hacia la pelvis',
      'Dejá que las rodillas caigan relajadas hacia los costados por su propio peso',
      'Extendé los brazos hacia atrás o relajalos a los costados',
      'Respirá largo y profundo, sintiendo cómo se expande y relaja toda la zona genital',
    ],
    tip: 'No empujes las rodillas hacia abajo; la gravedad hace todo el trabajo para descongestionar la pelvis.',
    phases: [
      { name: 'Apertura y Descompresión Somática', duration: 40, instruction: 'Dejá caer las rodillas y respirá a la pelvis', color: '#A8D8EA' },
      { name: 'Micro-Kegel suave en apertura', duration: 15, instruction: 'Contracción muy suave al 30% mientras sostenés la apertura', color: '#00C896' },
      { name: 'Relajación Total', duration: 30, instruction: 'Soltá toda tensión en perineo y glúteos', color: '#4A9EFF' },
    ],
    defaultReps: 1,
    defaultSets: 2,
  },

  goddess_squat: {
    id: 'goddess_squat',
    name: 'Sentadilla Jinete / Postura de la Diosa',
    category: 'strength',
    icon: '🥋',
    targetMuscle: 'Obturador interno + aductores + soporte de la próstata',
    benefit: 'Soporte somático a la próstata, presión y flujo vascular de alta intensidad',
    difficulty: 2,
    type: 'hold_and_pulse',
    description: 'Apertura de piernas muy amplia con pies hacia afuera a 45°, bajando la cadera con el torso erguido y manos al pecho en oración. Activa el músculo obturador interno, que forma las paredes laterales del piso pélvico.',
    howTo: [
      'Abrí las piernas el doble del ancho de hombros, con los pies a 45°',
      'Uní las palmas de las manos frente al pecho',
      'Bajá la pelvis flexionando rodillas hasta quedar casi paralelas al suelo',
      'Mantené el torso bien recto y erguido (no te inclines hacia adelante)',
      'Sostené la postura y sentí la carga directa en el piso pélvico',
    ],
    tip: 'Las rodillas deben mirar siempre en la misma dirección que las puntas de los pies.',
    phases: [
      { name: 'Sostén Isométrico', duration: 5, instruction: 'Mantené la postura baja con torso erguido', color: '#00C896' },
      { name: 'Pulso de Kegel en carga', duration: 3, instruction: 'Contraé el piso pélvico con fuerza en la posición baja', color: '#FFD700' },
      { name: 'Elevación suave', duration: 4, instruction: 'Subí lento sin bloquear rodillas y respirá', color: '#4A9EFF' },
    ],
    defaultReps: 8,
    defaultSets: 3,
  },
};

const EXERCISE_CATEGORIES = {
  kegel: { name: 'Kegel', label: 'Suelo Pélvico', color: '#00C896', icon: '💪', description: 'Ejercicios directos para el piso pélvico masculino' },
  strength: { name: 'Fuerza', label: 'Ejercicios Complementarios', color: '#4A9EFF', icon: '🏋️', description: 'Fortalecen glúteos y cadena posterior que soportan el piso pélvico' },
  stretch: { name: 'Estiramiento', label: 'Flexibilidad y Relajación', color: '#A8D8EA', icon: '🧘', description: 'Relajación y movilidad para un piso pélvico equilibrado' },
  breathing: { name: 'Respiración', label: 'Respiración y Conciencia', color: '#A8FF78', icon: '🫁', description: 'Técnicas de respiración para integrar y potenciar los Kegel' },
};

function getAllExercises() { return Object.values(EXERCISES); }
function getExerciseById(id) { return EXERCISES[id] || null; }
function getExercisesByCategory(category) { return Object.values(EXERCISES).filter(ex => ex.category === category); }
